name: Python Test
on:
  pull_request:
    branches: [main,muhammad,Mehmood]
    types: [closed]
  push:
    branches: [main,Mehmood,muhammad]

jobs:
  test:
    if: github.event.pull_request.merged == true || github.event.push==true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Specify the Python version you want to use

    
    - name: Run tests and coverage
      run: echo "Starting now"

    - name: Install dependencies
      run: make install
    
    - name: Lint
      run: make lint
    
    - name: Test
      run: make test
        
     
      
